# Generated by Django 4.2.11 on 2026-06-06 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campana_vacunacion', '0002_initial'),
        ('vacunas', '0001_initial'),
        ('manejo_usuarios', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='vacuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vacunas.vacuna'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='personal',
            name='centro_vacunacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campana_vacunacion.centrovacunacion'),
        ),
        migrations.AddField(
            model_name='historial',
            name='personal_a_cargo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacunaciones_realizadas', to='manejo_usuarios.personal'),
        ),
    ]
