# Generated by Django 4.2.11 on 2026-07-05 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manejo_usuarios', '0003_admin_telefono_personal_telefono_alter_historial_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
