# Generated by Django 6.0.6 on 2026-07-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manejo_usuarios', '0004_alter_historial_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
