# Generated by Django 4.2.11 on 2026-07-05 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campana_vacunacion', '0007_alter_direccion_id'),
        ('manejo_usuarios', '0006_alter_historial_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historial',
            name='vacuna',
        ),
        migrations.AddField(
            model_name='historial',
            name='campana',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campana_vacunacion.campaña'),
        ),
        migrations.AddField(
            model_name='historial',
            name='centro_vacunacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campana_vacunacion.centrovacunacion'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='historial',
            name='hora',
            field=models.TimeField(),
        ),
    ]
