# Generated by Django 6.0.7 on 2026-07-07 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manejo_usuarios', '0007_remove_historial_vacuna_historial_campana_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
