# Generated by Django 6.0.5 on 2026-06-02 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campana_vacunacion', '0001_initial'),
        ('manejo_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id_vacuna', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('stock_disponible', models.IntegerField(unique=True)),
                ('nombre_vacuna', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vacunacion',
            fields=[
                ('id_vacunacion', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('fecha_vacunacion', models.DateField()),
                ('observaciones', models.CharField(max_length=100)),
                ('centro_vacunacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campana_vacunacion.centrovacunacion')),
                ('vacuna_aplicada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vacunas.vacuna')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioRecibioVacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manejo_usuarios.usuario')),
                ('id_vacunacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vacunas.vacunacion')),
            ],
        ),
        migrations.CreateModel(
            name='VacunacionPorCampaña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_campaña', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campana_vacunacion.campaña')),
                ('id_vacunacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vacunas.vacunacion')),
            ],
        ),
    ]
