# Generated by Django 4.2.11 on 2026-06-06 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campana_vacunacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id_vacuna', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('stock_disponible', models.IntegerField(default=0)),
                ('nombre_vacuna', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vacunacion',
            fields=[
                ('id_vacunacion', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('fecha_vacunacion', models.DateField()),
                ('observaciones', models.CharField(max_length=100)),
                ('centro_vacunacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campana_vacunacion.centrovacunacion')),
                ('vacuna_aplicada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vacunas.vacuna')),
            ],
        ),
        migrations.CreateModel(
            name='VacunacionPorCampaña',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_campaña', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campana_vacunacion.campaña')),
                ('id_vacunacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vacunas.vacunacion')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioRecibioVacuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_vacunacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vacunas.vacunacion')),
            ],
        ),
    ]
