# Generated by Django 6.0.5 on 2026-06-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacunas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacuna',
            name='stock_disponible',
            field=models.IntegerField(default=0),
        ),
    ]
