# Generated by Django 6.0.6 on 2026-07-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacunas', '0003_alter_usuariorecibiovacuna_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariorecibiovacuna',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vacunacionporcampaña',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
