# Generated by Django 4.2.11 on 2026-07-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacunas', '0004_alter_usuariorecibiovacuna_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariorecibiovacuna',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vacunacionporcampaña',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
