# Generated by Django 4.2.11 on 2026-07-05 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campana_vacunacion', '0007_alter_direccion_id'),
        ('vacunas', '0005_alter_usuariorecibiovacuna_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacunacion',
            name='vacuna_aplicada',
        ),
        migrations.AddField(
            model_name='vacunacion',
            name='campana',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campana_vacunacion.campaña'),
        ),
        migrations.AddField(
            model_name='vacunacion',
            name='hora_vacunacion',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
