# Generated by Django 6.0.7 on 2026-07-07 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campana_vacunacion', '0009_alter_campaña_vacuna_alter_cita_campana_and_more'),
        ('vacunas', '0006_remove_vacunacion_vacuna_aplicada_vacunacion_campana_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariorecibiovacuna',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usuariorecibiovacuna',
            name='id_vacunacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='vacunas.vacunacion'),
        ),
        migrations.AlterField(
            model_name='vacunacion',
            name='campana',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='campana_vacunacion.campaña'),
        ),
        migrations.AlterField(
            model_name='vacunacion',
            name='centro_vacunacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='campana_vacunacion.centrovacunacion'),
        ),
        migrations.AlterField(
            model_name='vacunacionporcampaña',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vacunacionporcampaña',
            name='id_campaña',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='campana_vacunacion.campaña'),
        ),
        migrations.AlterField(
            model_name='vacunacionporcampaña',
            name='id_vacunacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='vacunas.vacunacion'),
        ),
    ]
