# Generated by Django 6.0.5 on 2026-06-02 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaña',
            fields=[
                ('id_campaña', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre_campaña', models.CharField(max_length=100)),
                ('descripcion_campaña', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado_campaña', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CentroVacunacion',
            fields=[
                ('id_centro', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre_centro', models.CharField(max_length=100)),
                ('comuna_centro', models.CharField(max_length=100)),
                ('region_centro', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=100)),
                ('calle', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonalCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id_cita', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('fecha_cita', models.DateField()),
                ('hora_cita', models.TimeField()),
                ('ubicacion_cita', models.CharField(max_length=100)),
                ('estado_cita', models.BooleanField()),
                ('cita', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campana_vacunacion.campaña')),
            ],
        ),
    ]
