# Generated by Django 4.2.11 on 2026-06-06 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manejo_usuarios', '0001_initial'),
        ('campana_vacunacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='paciente_citado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manejo_usuarios.paciente'),
        ),
        migrations.AddField(
            model_name='cita',
            name='personal_citado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manejo_usuarios.personal'),
        ),
        migrations.AddField(
            model_name='centrovacunacion',
            name='direccion_centro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campana_vacunacion.direccion'),
        ),
    ]
