# Generated by Django 6.0.5 on 2026-06-02 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campana_vacunacion', '0001_initial'),
        ('manejo_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='paciente_citado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manejo_usuarios.paciente'),
        ),
        migrations.AddField(
            model_name='centrovacunacion',
            name='direccion_centro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campana_vacunacion.direccion'),
        ),
        migrations.AddField(
            model_name='personalcita',
            name='cita',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campana_vacunacion.cita'),
        ),
        migrations.AddField(
            model_name='personalcita',
            name='personal_citado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manejo_usuarios.personal'),
        ),
        migrations.AddField(
            model_name='cita',
            name='personal_citado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_del_personal', to='campana_vacunacion.personalcita'),
        ),
    ]
