# Generated by Django 6.0.6 on 2026-07-04 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campana_vacunacion', '0003_campaña_centro_vacunacion_campaña_vacuna_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaña',
            name='centro_vacunacion',
        ),
        migrations.AddField(
            model_name='campaña',
            name='centros_vacunacion',
            field=models.ManyToManyField(blank=True, to='campana_vacunacion.centrovacunacion'),
        ),
    ]
