# Generated by Django 4.2.11 on 2026-07-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campana_vacunacion', '0006_alter_direccion_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
