# Generated by Django 6.0.6 on 2026-07-07 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campana_vacunacion', '0007_alter_direccion_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='intentos_recordatorio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cita',
            name='recordatorio_enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cita',
            name='ultimo_intento_recordatorio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
