# Generated by Django 6.0.7 on 2026-07-07 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campana_vacunacion', '0008_cita_intentos_recordatorio_cita_recordatorio_enviado_and_more'),
        ('vacunas', '0006_remove_vacunacion_vacuna_aplicada_vacunacion_campana_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaña',
            name='vacuna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='vacunas.vacuna'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='campana',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='campana_vacunacion.campaña'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='centro_vacunacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='campana_vacunacion.centrovacunacion'),
        ),
    ]
